### ISSUE TITLE
Require LPToken signature

### ISSUE THREAD

**Issue by doismellburning** [laterpay/django-laterpay#11]
https://github.com/laterpay/django-laterpay/pull/5 only checks the signature if it exists; [in the event of a missing signature/timestamp, it'll happily accept an arbitrary lptoken](https://github.com/laterpay/django-laterpay/commit/d449085871219e51b0adf99ec22efd56a8feb364#diff-fc7056ffd7f4671f7192dd7ec4eb6764R56)

**Comment by suligap** [comment]
We initialize `verified_lptoken` as `None` [here](https://github.com/laterpay/django-laterpay/blob/cc28c916d0236c7321aa4c804c2bcf8ac50b17af/djlaterpay/middleware.py#L32). If signature or timestamp are missing [it stays `None`](https://github.com/laterpay/django-laterpay/blob/cc28c916d0236c7321aa4c804c2bcf8ac50b17af/djlaterpay/middleware.py#L71-L72) and is set [here](https://github.com/laterpay/django-laterpay/blob/cc28c916d0236c7321aa4c804c2bcf8ac50b17af/djlaterpay/middleware.py#L74) as `None`. We test [those scenarios](https://github.com/laterpay/django-laterpay/blob/cc28c916d0236c7321aa4c804c2bcf8ac50b17af/tests/test_middleware.py#L42-L54).

**Comment by doismellburning** [comment]
Oops, yes, thanks, sorry!

What threw me was the difference in behaviour between "no token" and "an unverified token"

* With no token and no cookie, the user's redirected to `/identify`
* With a token but without an invalid signature, the user isn't redirected

If this behaviour is intended, it could probably really do with some clarifying logging please!

**Comment by suligap** [comment]
This behavior was intended (avoid creating a redirect loop). Good point about missing logs. Created #12 for that.

**Comment by doismellburning** [comment]
Ah, good point, thanks!

**Comment by doismellburning** [comment]
#12's long-merged, I think we can close this now! :)
